# Generated by Django 4.1.6 on 2023-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
