# Generated by Django 4.1.6 on 2023-04-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0003_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=10)),
                ('start_time', models.TimeField(blank=True)),
                ('lunch', models.TimeField(blank=True)),
                ('shift_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='medical_practice.doctor')),
            ],
        ),
    ]
