# Generated by Django 4.1.6 on 2023-04-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0004_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='shift_duration',
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(blank=True, choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=10),
        ),
    ]
