# Generated by Django 4.1.6 on 2023-04-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0005_remove_doctorschedule_shift_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='lunch',
            new_name='lunch_time',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
