# Generated by Django 4.1.6 on 2023-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0006_alter_user_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_notes',
            field=models.TextField(default='', max_length=300),
        ),
    ]
