# Generated by Django 4.1.6 on 2023-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0006_rename_lunch_doctorschedule_lunch_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='lunch_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
