# Generated by Django 4.1.6 on 2023-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0007_alter_doctorschedule_lunch_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=10),
        ),
    ]
