# Generated by Django 4.1.6 on 2023-04-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_practice', '0007_appointment_doctor_notes_appointment_patient_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_notes',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
